### ISSUE TITLE
animationRepeatCount 和 gif总帧数

### ISSUE THREAD

**Issue by LoveElaine** [ibireme/YYImage#1]
您好:

    需要咨询您两个问题
    1.我在使用使用过程中发现animationRepeatCount不起作用了，有时候也许需要播放几次后就停止应该怎么做呢?
    2.gif一共有多少帧怎么获取呢？animationImages 是NULL的

谢谢!

**Comment by ibireme** [comment]
YYImage 实现了 <YYAnimatedImage> 协议，这个协议里面包含有动画的参数，比如：

    YYImage *img = [YYImage imageNamed:@"test.gif"];
    [img animatedImageFrameCount]; // 帧数
    [img animatedImageLoopCount]; // GIF循环次数

使用时，是直接通过 UIImageView.image 属性来调整的，比如：

    UIImageView *imgView = [[YYAnimatedImageView alloc] initWithFrame:frame];
    imgView.image = img;
    YYImage *getImg = (YYImage *)imgView.img;

另外，GIF 的循环次数是 GIF 本身的属性，是只读的。如果你需要在运行时修改，你可以子类化 YYImage，然后添加一个 animatedImageLoopCount 属性。

**Comment by LoveElaine** [comment]
谢谢解答！

**Comment by suyuexin** [comment]
YYAnimatedImage只是能获取到loopCount但是不能设置,继承于YYImage怎么来改变呢?谢谢

**Comment by ibireme** [comment]
就是简单的继承啊。。举个例子：

    @interface MyImage : YYImage
    @property (nonatomic, assign) NSUInteger animatedImageLoopCount;
    @end

    @implementation MyImage {
        BOOL _loopCountChanged;
        NSUInteger _animatedImageLoopCount;
    }

    - (NSUInteger)animatedImageLoopCount {
        return _loopCountChanged ? _animatedImageLoopCount : [super animatedImageLoopCount];
    }

    - (void)setAnimatedImageLoopCount:(NSUInteger)animatedImageLoopCount {
        _loopCountChanged = YES;
        _animatedImageLoopCount = animatedImageLoopCount;
    }

    @end

**Comment by suyuexin** [comment]
非常感谢,我只是关注setter方法了,忘记把他们给关联起来了.
