### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by devSC** [ibireme/YYImage#10]
用Cocoapods集成YYKit后, 在自己工程中通过:
```
        YYImage *image = [YYImage imageNamed:@"loading2@3x.png"];
```
来加载Apng文件时, 获取的image中,decoder为nil.
但将文件添加进YYKit-demo中, 通过同样的方法, 可以加载并显示出来. 
请问换需要其他配置么?

**Comment by ibireme** [comment]
在 Build Setting 中，把 Compress PNG files 改为 NO 就可以了。
这个选项为 YES 时，Xcode 会在打包时压缩所有的 PNG 文件，这会让 APNG 失去动画。
