### ISSUE TITLE
有个webp的图片转出来image是nil，求帮忙

### ISSUE THREAD

**Issue by mewehk** [ibireme/YYImage#11]
[pic1.webp.zip](https://github.com/ibireme/YYImage/files/97503/pic1.webp.zip)

**Comment by mewehk** [comment]
这个webp图片用chrome是可以打开的，但是就是转出来没有image

**Comment by ibireme** [comment]
这幅图片是一张受损图片，用 Chrome 打开能注意到图片最下方解码是有问题的。
调用 WebPDecode() 时，函数会返回错误码 `VP8_STATUS_NOT_ENOUGH_DATA`，如果忽略这个错误继续解码也是能解出来的，但那可能会造成不好的结果。。
