### ISSUE TITLE
使用cocoapods 导入 YYImage和YYWebImage时始终在DEBUG版本不支持WebP

### ISSUE THREAD

**Issue by laughing25** [ibireme/YYImage#112]
target :YoshopPro do

platform :ios, "8.0"

pod 'YYWebImage'
pod 'YYImage'
pod 'YYImage/WebP'

end

切换release模式时可以载入WebP,但是debug时，就加载不了WebP图片了，有人遇到过同样的情况吗？

**Comment by iTofu** [comment]
@laughing25 
有解决方案吗？为什么关了这个 issue 呢？
