### ISSUE TITLE
更新下pod库

### ISSUE THREAD

**Issue by onezens** [ibireme/YYImage#115]
因为我们的项目使用了YYImage 1.0.4， 我们项目的另外一个组件库使用了libwebp的库，所以冲突了，导致显示不了webp格式的图片

最新的仓库加了libwebp的subspec，但是1.0.4的tag没有

麻烦大神更新一版pod，谢谢

**Comment by onezens** [comment]
麻烦pod更新下，比较急 @ibireme

**Comment by caicai0525** [comment]
请问你是怎么解决的这个问题

**Comment by Jacky-LinPeng** [comment]
后面是咋解决？ 没后续了？
