### ISSUE TITLE
请问 ：webp.framework中45 duplicate symbols for architecture arm64怎么解决

### ISSUE THREAD

**Issue by LBJYZY** [ibireme/YYImage#12]
/Classes/MSExpand/Vendor/YYImage/WebP.framework/WebP(libwebpdsp_la-yuv.o)
/Classes/MSExpand/Vendor/YYImage/WebP.framework/WebP(libwebpdspdecode_la-yuv.o)
duplicate symbol _WebPInitSamplers in:
/Classes/MSExpand/Vendor/YYImage/WebP.framework/WebP(libwebpdsp_la-yuv.o)
/Classes/MSExpand/Vendor/YYImage/WebP.framework/WebP(libwebpdspdecode_la-yuv.o)
duplicate symbol _WebPSamplerProcessPlane in:
/Classes/MSExpand/Vendor/YYImage/WebP.framework/WebP(libwebpdsp_la-yuv.o)
/Classes/MSExpand/Vendor/YYImage/WebP.framework/WebP(libwebpdspdecode_la-yuv.o)
ld: 45 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ibireme** [comment]
如果不需要 WebP 支持，那可以直接把 WebP.framework 删掉。

需要 WebP 的话，这里可以检查是否有 WebP 库的冲突，如果还有问题，推荐用 CocoaPods 安装。
