### ISSUE TITLE
BAD_ACCESS on YYImageCoder.m

### ISSUE THREAD

**Issue by Lailan** [ibireme/YYImage#129]
When I call the method YYCGImageCreateEncodedWebPData(lista[i].cgImage!, false, 0, 0, YYImagePreset.default) and step an image with transparency as parameter, the YYImageCoder.m returns me a BAD_ACCESS error, more precisely on the line: 
  
if (! WebPPictureImportRGBA (& picture, buffer.data, (int) buffer.rowBytes)) goto fail;

Can someone help me?

**Comment by pballart** [comment]
I am having the same issue. How did you solve it?

**Comment by Lailan** [comment]
Hi @pballart 
I solved. 
Check my project. 
https://github.com/Lailan/Figurinhas-Whastapp/tree/master/StickersWhatsapp/WhatsApp

I used the YYImagecoder from WhatsApp repository.
