### ISSUE TITLE
YYImageEncoder Bug

### ISSUE THREAD

**Issue by linlinyao1** [ibireme/YYImage#14]
https://github.com/ibireme/YYImage/blob/master/YYImage/YYImageCoder.m#L2727

> +(NSData *)encodeImageWithDecoder:(YYImageDecoder *)decoder type:(YYImageType)type quality:(CGFloat)quality {
    if (!decoder || !decoder.frameCount == 0) return nil;
    YYImageEncoder *encoder = [[YYImageEncoder alloc] initWithType:type];
    encoder.quality = quality;
    for (int i = 0; i < decoder.frameCount; i++) {
        UIImage *frame = [decoder frameAtIndex:i decodeForDisplay:YES].image;
        [encoder addImageWithData:UIImagePNGRepresentation(frame) duration:[decoder frameDurationAtIndex:i]];
    }
    return encoder.encode;
}

这里应该是 decoder.frameCount == 0 吧？？

**Comment by ibireme** [comment]
Fixed
