### ISSUE TITLE
Latest YYImage version doesn't decode WebP files

### ISSUE THREAD

**Issue by ex3ndr** [ibireme/YYImage#17]
0.9.3 works fine, but 1.0 returns nil on any webp image.

**Comment by ibireme** [comment]
The WebP library's install size is too large, and some people don't need it, so I moved it to an optional subspec since version 1.0. You may install the subspec with `pod 'YYImage/WebP'`. See alse: https://github.com/ibireme/YYImage#installation .

I will add `CHANGELOG` or `release notes` later.

**Comment by ibireme** [comment]
Added release notes:
https://github.com/ibireme/YYImage/releases
