### ISSUE TITLE
Memory Leak in 1.0

### ISSUE THREAD

**Issue by philiplaskowski** [ibireme/YYImage#18]
I am using 1.0 to animate a sequence of PNGs (380 in total @ 60 fps) and have run into serious memory leak issues with that cause the app to crash after a while.

Xcode console first prints this continuously:
`<Error>: CGBitmapContextInfoCreate: unable to allocate 3469440 bytes for bitmap data`

After a while the more lines appear (again printed continuously):
`<Error>: CGBitmapContextInfoCreate: unable to allocate 3469440 bytes for bitmap data`
`malloc: *** mach_vm_map(size=8388608) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug`

After a few more seconds of animating the app crashes.

I tried to find the responsible part with Instruments ("Leaks") and found the following leak causing the majority of the memory usage (there are hundreds of UIImages retained):

Collapsed:
<img width="1025" alt="bildschirmfoto 2016-03-09 um 13 51 19" src="https://cloud.githubusercontent.com/assets/13064797/13635769/3b454da2-e5fe-11e5-9ba1-74895f244645.png">

Expanded:
<img width="1026" alt="bildschirmfoto 2016-03-09 um 13 51 26" src="https://cloud.githubusercontent.com/assets/13064797/13635775/43da9a1c-e5fe-11e5-92cb-daae3a4cbddf.png">

Filtered ("unpaired" only):
<img width="1024" alt="bildschirmfoto 2016-03-09 um 14 04 35" src="https://cloud.githubusercontent.com/assets/13064797/13636046/ea91172c-e5ff-11e5-86ab-57846383c625.png">

I tried setting `maxBufferSize` to a reasonable value, but that didn't help. Any ideas on what might cause the severe leaks?

**Comment by ibireme** [comment]
I created a new project with 380 png files, there's no problem. But when I add the [AnimatedGIFImageSerialization](https://github.com/mattt/AnimatedGIFImageSerialization) library to the project, memory leak happened.

`AnimatedGIFImageSerialization` made some method swizzle on `UIImage` and it may cause some potential problem. I suggest to remove it and use `YYImage` `YYAnimatedImageView` to play GIF animation.

**Comment by philiplaskowski** [comment]
@ibireme Thank you very much for the fast support! This solved the problem!
By the way `YYImage` is the best animated image framework I have found so far, great work!
