### ISSUE TITLE
请问YYImage或者YYWebImage有对gif图压缩的功能嘛？

### ISSUE THREAD

**Issue by acBool** [ibireme/YYImage#19]
当gif图比较大的时候，YYImage或者YYWebImage有对gif压缩的方法嘛？

**Comment by ibireme** [comment]
YYImage 里，GIF 的解码和编码都是直接调用 ImageIO 的逻辑实现的。

你说的 `大` 是指文件体积大，还是图片分辨率大？
如果说是体积大的话，那这里没办法。GIF 的压缩和视频编码有类似的地方，想做优化的话非常复杂而且需要消耗大量的 CPU。如果是分辨率大，那可以先把每帧的图片用 YYImageDecoder 取出来，每张都 resize 然后传给 YYImgaeEncoder 编码。

**Comment by RedeemD** [comment]
这样操作的结果会导致原本 GIF 的公共区域优化失效, 只是拼接了所有帧的图片
结果很可能比原本的图片还要大

有没有什么合适的解决方案呢
