### ISSUE TITLE
读取Image.xcassets

### ISSUE THREAD

**Issue by melvin7** [ibireme/YYImage#2]
我测试发现YYImage 现在读取Image.xcassets内的图片是无法读取成功的。

**Comment by ibireme** [comment]
是的，目前 [YYImage imageNamed] 这个方法只支持从 Main Bundle 中查找单个图片，而且也没有缓存。
如果用 assets 来管理图片的话，还是推荐用 UIImage。

**Comment by chengxianghe** [comment]
那如果用YYImage,项目就不能用Image.xcassets了么,我只是疑问,因为xcassets里还是有很多设置可以操作的

**Comment by ibireme** [comment]
是啊。。assets 里有很多苹果自定义的配置，而且也不能支持 WebP 之类的东西。。所以还是推荐用 UIImage。。

以后有时间我会试试看能否做一下兼容。

**Comment by shaveKevin** [comment]
使用yyimage 支持 svg 和pdf 格式的图片吗？

**Comment by ibireme** [comment]
目前不支持。
ImageIO 解码 SVG/PDF 有问题。PDF 倒是可以用[其他](https://github.com/ibireme/YYKit/blob/master/YYKit/Base/UIKit/UIImage%2BYYAdd.h#L62-L87)系统方法解码成图像，但是再编码回 PDF 就不行了。

**Comment by shaveKevin** [comment]
恩 pdf的系统能够通过[UIImage  imagenamed:"xx"] 可以进行加载  用SVG的时候 我使用了 SVGKit中 SVGImage  来加载 发现效果不是那么令人满意。

**Comment by ibireme** [comment]
之所以能够用 `[UIImage imagenamed:"xx"]` 来加载 pdf，是因为打包时 Xcode 把 PDF 转换成了 PNG。。

SVG（和 PDF）都是很复杂的格式，第三方库支持一般都不会太完善，而且这些矢量图的绘制，会随着图像的复杂程度增加而消耗更多的 CPU 资源（想想 Flash 在 PC 上的表现）。这在 PC 上不是什么大问题，但在移动端就难以控制了。

**Comment by shaveKevin** [comment]
恩恩  好的明白了。
