### ISSUE TITLE
Carthage issue

### ISSUE THREAD

**Issue by alex-hoang** [ibireme/YYImage#20]
Hi, 

We're using YYImage with imoji-sdk (https://github.com/alex-hoang/imoji-ios-sdk/tree/carthage). 

We're running into an issue trying to enable WebP by default while using the latest YYImage.framework compiled using carthage. With CocoaPods, the WebP dependency works nicely since all the source files are compiled by pod generated workspace. However with Carthage, the WebP dependency doesn't get detected even when added manually.

Any ideas on how to address that? Thanks!

**Comment by ibireme** [comment]
https://github.com/ibireme/YYImage#carthage

> Notice: carthage framework doesn't include WebP component, if you want to support WebP format, use CocoaPods or install manually.

I don't know how to add a static library dependency into Carthage framework... You may fork the project and add the `WebP.framework` to `YYImage.xcodeproj`:
<img width="1516" alt="2016-03-23 11 42 34" src="https://cloud.githubusercontent.com/assets/839283/13975081/c0e90ebe-f0ec-11e5-853d-902aafbfbe61.png">
