### ISSUE TITLE
Cannot play APNG in demo project

### ISSUE THREAD

**Issue by mumuu** [ibireme/YYImage#21]
Demo

**Comment by ibireme** [comment]
Fixed
貌似新版 Xcode 中默认移除了 png 的元数据，导致 apng 失效，注意把这两个选项关掉：
<img width="587" alt="2016-03-25 11 24 57" src="https://cloud.githubusercontent.com/assets/839283/14037328/32ffa6f2-f27d-11e5-887f-be1bcd35e9d9.png">

**Comment by ibireme** [comment]
Fixed
