### ISSUE TITLE
Possible memory leaks

### ISSUE THREAD

**Issue by ngheungyu** [ibireme/YYImage#22]
Hello, thanks for making this library!

I'm just referring to FBInfer's report, appreciate it if they can be fixed!

Cheers.
--------------------------------Report begins-----------------------------------------------
Pods/YYImage/YYImage/YYImageCoder.m:663: error: MEMORY_LEAK
   memory dynamically allocated by call to YYCGColorSpaceGetDeviceRGB() at line 663, column 36 is not reachable after line 663, column 5
  661.   
  662.   BOOL YYCGColorSpaceIsDeviceRGB(CGColorSpaceRef space) {
  663. >     return space && CFEqual(space, YYCGColorSpaceGetDeviceRGB());
  664.   }
  665.   

Pods/YYImage/YYImage/YYImageCoder.m:667: error: MEMORY_LEAK
   memory dynamically allocated by call to YYCGColorSpaceGetDeviceGray() at line 667, column 36 is not reachable after line 667, column 5
  665.   
  666.   BOOL YYCGColorSpaceIsDeviceGray(CGColorSpaceRef space) {
  667. >     return space && CFEqual(space, YYCGColorSpaceGetDeviceGray());
  668.   }
  669.   

Pods/YYImage/YYImage/YYImageCoder.m:887: error: MEMORY_LEAK
   memory dynamically allocated by call to YYCGColorSpaceGetDeviceRGB() at line 887, column 81 is not reachable after line 887, column 32
  885.           CGBitmapInfo bitmapInfo = kCGBitmapByteOrder32Host;
  886.           bitmapInfo |= hasAlpha ? kCGImageAlphaPremultipliedFirst : kCGImageAlphaNoneSkipFirst;
  887. >         CGContextRef context = CGBitmapContextCreate(NULL, width, height, 8, 0, YYCGColorSpaceGetDeviceRGB(), bitmapInfo);
  888.           if (!context) return NULL;
  889.           CGContextDrawImage(context, CGRectMake(0, 0, width, height), imageRef); // decode

Pods/YYImage/YYImage/YYImageCoder.m:2055: error: MEMORY_LEAK
   memory dynamically allocated by call to YYCGColorSpaceGetDeviceRGB() at line 2055, column 91 is not reachable after line 2055, column 40
  2053.                   }
  2054.               } else {
  2055. >                 CGContextRef context = CGBitmapContextCreate(NULL, _width, _height, 8, 0, YYCGColorSpaceGetDeviceRGB(), kCGBitmapByteOrder32Host | kCGImageAlphaPremultipliedFirst);
  2056.                   if (context) {
  2057.                       CGContextDrawImage(context, CGRectMake(0, _height - height, width, height), imageRef);

Pods/YYImage/YYImage/YYImageCoder.m:2197: error: MEMORY_LEAK
   memory dynamically allocated by call to YYCGColorSpaceGetDeviceRGB() at line 2197, column 75 is not reachable after line 2197, column 9
  2195.       if (!_blendCanvas) {
  2196.           _blendFrameIndex = NSNotFound;
  2197. >         _blendCanvas = CGBitmapContextCreate(NULL, _width, _height, 8, 0, YYCGColorSpaceGetDeviceRGB(), kCGBitmapByteOrder32Host | kCGImageAlphaPremultipliedFirst);
  2198.       }
  2199.       BOOL suc = _blendCanvas != NULL;

Pods/YYImage/YYImage/YYImageCoder.m:2416: error: MEMORY_LEAK
   memory dynamically allocated to gifProperty by call to alloc() at line 2414, column 37 is not reachable after line 2416, column 9
  2414.           NSDictionary *gifProperty = @{(__bridge id)kCGImagePropertyGIFDictionary:
  2415.                                           @{(__bridge id)kCGImagePropertyGIFLoopCount: @(_loopCount)}};
  2416. >         CGImageDestinationSetProperties(destination, (__bridge CFDictionaryRef)gifProperty);
  2417.       }
  2418.

**Comment by ibireme** [comment]
Thanks for you report. Infer reported two memory leaks:

1. `YYCGColorSpaceGetDeviceRGB()` and `YYCGColorSpaceGetDeviceGray()` returns a singleton value, it's not a memory leak, Infer did not understand it.

2. `gifProperty` is created with `@{}` and the memory is managed by ARC, I don't know why Infer determine it as a memory leak...

**Comment by ngheungyu** [comment]
Thanks, if so then it's all good!
