### ISSUE TITLE
请问有把jpg/png转成webp格式的方法吗？

### ISSUE THREAD

**Issue by am1993421** [ibireme/YYImage#23]
现在有个问题就是 上传图片过度压缩导致图片不清晰 不压缩又太大导致上传太慢 后来想到转webp格式之后上传但这个过程CPU飙好高 不知道YYImage能否解决这样的问题呢

**Comment by ibireme** [comment]
webp 的编码本身就比 png、jpg 要消耗更多 CPU 资源，这个换哪个库都是改不了的。

推荐先把图片缩放到较小分辨率，之后再压缩。

**Comment by am1993421** [comment]
不知道QQ或者微信是怎样做的呢？看他们这方面似乎做的很好 我找了蛮久资料也找不到好的解决方法 突然想到可能你对这块有点研究所以想请教一下你

**Comment by ibireme** [comment]
微信后台慢慢发，QQ发送有进度条，我觉得一点都不快。。
