### ISSUE TITLE
无法加载七牛图片

### ISSUE THREAD

**Issue by Eventlengbinbin** [ibireme/YYImage#25]
http://moshtest.qiniudn.com/71/0d/d8/18031458b31580534195fc372c.jpg?imageView2/1/w/480/h/400/q/80

七牛存储的图片带参数的地址一直显示不了图片。请问这部分应该怎么处理

**Comment by ibireme** [comment]
YYImage 这个库只负责图片编解码和播放，并不会处理网络请求啊。。这应该是 YYWebImage 的 Issue 吧？

注意看一下 App 配置里是否禁用了 https 安全访问，另外，用手机浏览器直接打开看看，是不是 DNS 访问等网络问题。

**Comment by Eventlengbinbin** [comment]
sorry.  发错位置了。 网页显示是正常的， 我们服务器没做https支持。 所以肯定开了。 我去webImage那头提问。。。
