### ISSUE TITLE
Alamofire upload

### ISSUE THREAD

**Issue by Ybrin** [ibireme/YYImage#26]
I tried uploading an webp image with Alamofire like that

```Swift
Alamofire.upload(
		.POST,
	"https://example.com/upload",
	multipartFormData: { multipartFormData in
		multipartFormData.appendBodyPart(data: data, name: "image", fileName: "file.webp", mimeType: "image/webp")
	},
	encodingCompletion: { encodingResult in
		switch encodingResult {
		case .Success(let upload, _, _):
			print("Success!")
		case .Failure(let encodingError):
			print("Failure!")
		}
	}
)
```

where `data` is an `UIImage` which was encoded using `YYImageEncoder` like that:

```Swift
let webpEncoder = YYImageEncoder(type: .WebP)
webpEncoder?.quality = 0.8
webpEncoder?.addImage(image, duration: 0)
let data = webpEncoder?.encode()
```

The server should save the uploaded image and it worked until now but if I use the YYImageEncoder to get the webp representation, it fails with `502` and the error is the following:

> [Result]: FAILURE: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}

Like I said before, it works well with `UIImageJPEGRepresentation(image, 0.8)` but not with `YYImageEncoder`.
What exactly does the `encode()` method return? Is it possible to do an Multipart upload with the `YYImageEncoder` data?

**Comment by ibireme** [comment]
The `encode()` method returns image data (NSData) or nil if failed, nothing special.

You can call `YYImageWebPAvailable() `to check whether the WebP component is installed correctly. If the WebP component is not installed, the `encode()` method always returns nil for WebP format.

**Comment by Ybrin** [comment]
I am sorry, this was something totally different. Thank you anyway.
