### ISSUE TITLE
合成webp异常

### ISSUE THREAD

**Issue by jayi** [ibireme/YYImage#29]
我在应用里用两帧图片合成的 webp，底下有一片色块。
使用的YYImage的版本是1.0.1

两张图片是一样的，只有贴纸在动，可能是编码成 webp 的问题，发上来请教一下。
不是必现的，目前只见到一例。

合成后的 Webp
![](http://image.17wado.com/U47567/TOPIC_U47567_1461484671592_ANIMATED_750-750wh.webp)

拆成两帧后
![](http://image.17wado.com/U47567/1e1d2f238254b30d57647da4755404c76dd7672c.jpg)

**Comment by ibireme** [comment]
目前没看出来代码里的问题。。

希望能提供一下合成前的两张原始图片，和相关调用代码来看一下。

**Comment by jayi** [comment]
```objc
// UIImage category
- (NSData *)lx_webpData {
    if (self.images.count == 0) {
        NSData *data = [YYImageEncoder encodeImage:self type:YYImageTypeWebP quality:0.75];
        return data;
    } else {
        YYImageEncoder *webpEncoder = [[YYImageEncoder alloc] initWithType:YYImageTypeWebP];
        webpEncoder.loopCount = 0;
        for (UIImage *img in self.images) {
            [webpEncoder addImage:img duration:GIF_PLAY_INTERVAL];
        }
        return [webpEncoder encode];
    }
}
```
代码如上。
图片是用户发的，没有原始图片。。
没有复现出来，现在也只看到一个😂

**Comment by jayi** [comment]
两帧图片都是使用
```objc
- (BOOL)drawViewHierarchyInRect:(CGRect)rect afterScreenUpdates:(BOOL)afterUpdates;
```
生成的

**Comment by ibireme** [comment]
应该与这种生成图片的方法没关系。。

目前我能想到的可能出现问题的地方：image 取出 bitmap、bitmap 转成 webp、webp 打包成 animated webp、最终图像的数据传输。如果能有复现的方法，那就能确定问题产生的地方了，不然现在定位不了是在哪一步产生的问题。

**Comment by jayi** [comment]
嗯，那我再观察一下，看能不能复现。

谢谢~

**Comment by ibireme** [comment]
目前无法复现，先关掉问题。
如果能复现或者有原始图片可以 reopen。
