### ISSUE TITLE
关于动态图循环的疑问

### ISSUE THREAD

**Issue by suyuexin** [ibireme/YYImage#3]
默认无限循环的动态图可以正常的开始(startAnimating)和停止(stopAnimating);
假如动态图本身就是播放3次然后停止,停止后再startAnimating是没有作用的;
当然这不是YYImage的问题,YYImage还是很好用的,假如你知道关于这方面的问题的话,欢迎指教.

**Comment by ibireme** [comment]
UIImageView 的这个 start  和 stop 有时是会出现奇奇怪怪的问题。。
所以使用的时候，也只能多尝试一下了。
