### ISSUE TITLE
YYSpriteSheetImage has memory issues?

### ISSUE THREAD

**Issue by curno** [ibireme/YYImage#30]
Hi, I use YYLabel to display text with emoji in a message app. In the text parser the the label, I returned a YYSpriteSheetImage (with is also a UIImage) attachment.

When the message shows, the memory uses grows even I don't do anything. And after 4 or 5 times of memory warning, the app crashes.

This problem should be reproduced easily when there are about 50 emojis showing at the same time, the memory grows fast.

Also, when I check this with the Allocation profiler, I saw a massive CG Raster Data memory not being deallocated.
Please help me about where I was doing wrong, I am despairing

**Comment by ibireme** [comment]
<img width="452" alt="2016-04-28 3 03 08" src="https://cloud.githubusercontent.com/assets/839283/14877869/6ab202d0-0d52-11e6-98c6-51d1e323f63c.png">

I'v tested add 10 sprite image in a same view, the memory usage is normal but the cpu usage is very high. 

If you use sprite image in a single view, it will decode all images into memory and it may cause memory warning. I recommend to use the frame based image or animated image (GIF/APNG/WebP) to reduce memory and CPU cost.
