### ISSUE TITLE
more image into animations

### ISSUE THREAD

**Issue by TeeHom** [ibireme/YYImage#32]
more image into animations,that will call merry issues.

**Comment by ibireme** [comment]
merry issues?

**Comment by TeeHom** [comment]
好吧，我用中文，英文不是太好，就是我的需求是这样的，我的一组图片好多，一组都有上百张图片，使用YYAnimationImageView加进去后，cpu占用很大，

**Comment by ibireme** [comment]
如果都是动态图，那可以尝试考虑缩小图片尺寸。。。
如果希望 CPU 资源占用小，那就要提前解码图片到内存，可那样内存就会受不了。资源超过设备上限的话，只能在其中某个方面做些妥协了。
