### ISSUE TITLE
大图转webp时，内存暴增

### ISSUE THREAD

**Issue by mewehk** [ibireme/YYImage#4]
22M的图片用YYImageEncoder转webp文件时，内存直接飙到1G了，然后crash了，怎么解啊

**Comment by ibireme** [comment]
22M的图片。。你也敢丢到手机里去编码哈哈哈！！

嗯。。这个没办法，编码解码都是直接用 libwebp 做的，要保证低内存消耗，只能先压缩成小图再处理了。
