### ISSUE TITLE
Wrong code in YYImageCoder.m

### ISSUE THREAD

**Issue by wysaid** [ibireme/YYImage#41]
The code below in YYImageCode.m at line 1405-1415
The buffer named "tmp" is never used, please fix.
And the code segment is never run...
# 

`
if (iter.x_offset != 0 || iter.y_offset != 0) {

```
void *tmp = calloc(1, destLength);

if (tmp) {

    vImage_Buffer src = {destBytes, canvasHeight, canvasWidth, bytesPerRow};

    vImage_Buffer dest = {destBytes, canvasHeight, canvasWidth, bytesPerRow};

    vImage_CGAffineTransform transform = {1, 0, 0, 1, iter.x_offset, -iter.y_offset};

    uint8_t backColor[4] = {0};

    vImageAffineWarpCG_ARGB8888(&src, &dest, NULL, &transform, backColor, kvImageBackgroundColorFill);

    memcpy(destBytes, tmp, destLength);

    free(tmp);

}
```

}

`

**Comment by wysaid** [comment]
And also there's a waste of memory in the alignment calculation.
code: 
```
hasAlpha = config.input.has_alpha;
bitsPerComponent = 8;
bitsPerPixel = 32;
bytesPerRow = YYImageByteAlign(bitsPerPixel / 8 * canvasWidth, 32);
```
The image can have 3 or 4 channels.  But you're not handling the two situations.
So if an image has no alpha channel, 25% of additional useless memory is allocated.

**Comment by ibireme** [comment]
Thanks~

1. The bug is fixed: https://github.com/ibireme/YYImage/commit/b659f9055d1714b4505589b44d34696c33b3aae2

2. Core Animation prefer to use `bgrA8888` (kCGBitmapByteOrder32Host | kCGImageAlphaPremultipliedFirst) data to display image, see also: https://github.com/path/FastImageCache#byte-alignment
