### ISSUE TITLE
Orientation为右的UIImage编码错误

### ISSUE THREAD

**Issue by jayi** [ibireme/YYImage#5]
NSData *data = [YYImageEncoder encodeImage:image type:YYImageTypeWebP quality:0.75];

用以上代码对一张 Orientation 为右的 UIImage 进行编码时，发现编码后得到图片是错误的，如下图。
![img_0492](https://cloud.githubusercontent.com/assets/3376305/11927907/b5dad118-a80a-11e5-9fc0-63b14ff1bedc.JPG)

定位到是 YYImageCoder.m 下 YYCGImageCreateAffineTransformCopy 的问题。水平有限，这个地方看不懂，提上来请大神修复。

**Comment by ibireme** [comment]
目前可以先把 UIImage 的 orientation 去掉后再编码。。

后面会考虑下增加 orientation 支持。

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/YYImage/commit/b5b08df8025a0d9123cd3e93815f32f22a78ff1f

**Comment by rakuyoMo** [comment]
这个问题在 iOS 12 上重新出现了... Orientation 为 左/右 时，调用 yy_imageDataRepresentation 方法会导致图片出现乱码问题。
