### ISSUE TITLE
issue:Multiple locks on web thread not allowed!

### ISSUE THREAD

**Issue by cloudhm** [ibireme/YYImage#52]
求助：加载图片进度条展示使用UCZProgressView，使用后会出现WTFCrash
`2016-08-12 14:11:46.978 mode[17853:573412] bool _WebTryThreadLock(bool), 0x7fc0828f7300: Multiple locks on web thread not allowed! Please file a bug. Crashing now...
1   0x10aabe34e WebRunLoopLock(__CFRunLoopObserver*, unsigned long, void*)
2   0x1066acc37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
3   0x1066acba7 __CFRunLoopDoObservers
4   0x1066a26c4 __CFRunLoopRun
5   0x1066a20f8 CFRunLoopRunSpecific
6   0x10aabe325 RunWebThread(void*)
7   0x10773599d _pthread_body
8   0x10773591a _pthread_body
9   0x107733351 thread_start`
<img width="733" alt="screen shot 2016-08-12 at 2 24 41 pm" src="https://cloud.githubusercontent.com/assets/12466998/17614208/00217a02-6097-11e6-8388-13e306cdf157.png">
<img width="1076" alt="screen shot 2016-08-12 at 2 23 00 pm" src="https://cloud.githubusercontent.com/assets/12466998/17614209/00b66df6-6097-11e6-940b-e873b1ea5133.png">

**Comment by ibireme** [comment]
这个是 WebThread 的崩溃啊，与 UCZProgressView 或者 YYWebImage 应该没关系吧。。

**Comment by cloudhm** [comment]
这是在一个次级页面collectionview中显示多张图片，这么写就容易出现这个问题
line 95和103注释掉，就没出现这个问题

**Comment by coderChrisLee** [comment]
> 这是在一个次级页面collectionview中显示多张图片，这么写就容易出现这个问题
> line 95和103注释掉，就没出现这个问题

我也出现这个报错，本以为是 Webview 的问题，跳转其他页面正常，但跳转某个界面大概率会出现这个崩溃，注释掉 webview 也还是会出现。 搜索一些结果说跟 Runloop 有关，刚好看到你这个issue 说是加载进度条 UCZProgressView 导致崩溃。 刚好我们这个有问题的界面 Cell 上有用到 这个进度 progressView ，这个进度view 在初始化设置进度后会开启一个 runLoop ，写法应该是有问题：
`- (void)setProgress:(CGFloat)progress animated:(BOOL)animated {
    if (self.indeterminate) {
        self.indeterminate = NO;
        [[NSRunLoop currentRunLoop] runUntilDate:[NSDate date]];
    }`
