### ISSUE TITLE
IOS9中可以使用pdf格式图片

### ISSUE THREAD

**Issue by yimouleng** [ibireme/YYImage#6]
IOS9中可以使用pdf格式图片，极大的减轻了图片的切图，不用再切@2x,@3x，那么YYImage 是否支持pdf格式图片的加载和优化呢？ 我看RM上并没有写着支持，

**Comment by ibireme** [comment]
目前没有。你可以先试试这个方法的实现：https://github.com/ibireme/YYKit/blob/master/YYKit/Base/UIKit/UIImage%2BYYAdd.h#L62-L87

稍后我会尝试加到 YYImage 里。

**Comment by yimouleng** [comment]
很感谢，我会关注的
