### ISSUE TITLE
支持7.1 吗

### ISSUE THREAD

**Issue by Ewithome** [ibireme/YYImage#7]

**Comment by ibireme** [comment]
目前支持 iOS 6.0 ~ 9.x

**Comment by Ewithome** [comment]
我在4S 上7.1  上遇到了  dyld: Symbol not found: _CTRubyAnnotationCreate
  Referenced from: /var/mobile/Applications/8EA63465-DFA5-41C2-95C8-95D6CDC744E8/ZZChatiPhone.app/ZZChatiPhone
  Expected in: /System/Library/Frameworks/CoreText.framework/CoreText
 in /var/mobile/Applications/8EA63465-DFA5-41C2-95C8-95D6CDC744E8/ZZChatiPhone.app/ZZChatiPhone
warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.

**Comment by Ewithome** [comment]
真机

**Comment by ibireme** [comment]
这不是 YYIMage 里的代码，这应该是 YYTextRubyAnnotation 或其它文本框架里面带的。

我已经测试过从 iOS 6~9 的真机和模拟器，都可以顺利编译并运行。如果你遇到的只是警告，继续运行不会崩溃，那可以忽略掉，不会造成问题。如果你遇到的是崩溃，那你可以检查下 YYTextRubyAnnotation 这个类、或者你的 App 中其他文本库中是否有实际调用 RubyAnnotation 相关的方法。

**Comment by Ewithome** [comment]
是蹦了

**Comment by ibireme** [comment]
那检查下你的代码吧，是否调用了 CTRubyAnnotation 相关的方法。CTRuby 只在 iOS 8 以上才支持，相关方法上应该会有版本号支持的说明。

**Comment by Ewithome** [comment]
[YYTextLayout layoutWithContainer:container text:_questionContentLab.attributedText]

 for (int i = 0; i < [arr count]; i ++) {
        NSString *messageString = arr[i];
        if ([messageString hasPrefix:kEmojiContentSign]) {//表情
            messageString = [messageString stringByReplacingOccurrencesOfString:kEmojiContentSign withString:@""];
            YYImage *image = [YYImage imageNamed:messageString];
            image.preloadAllAnimatedImageFrames = YES;
            YYAnimatedImageView *imageView = [[YYAnimatedImageView alloc] initWithImage:image];
            imageView.autoPlayAnimatedImage = NO;
            [imageView startAnimating];
            
            NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithContent:imageView contentMode:UIViewContentModeCenter attachmentSize:imageView.size alignToFont:font alignment:YYTextVerticalAlignmentBottom];
            [text appendAttributedString:attachText];
            
        }else if([messageString isEmpty]){//空
        }else{//文字
            [text appendAttributedString:[[NSAttributedString alloc] initWithString:messageString attributes:nil]];
        }
    }

    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:_questionContentLab.attributedText];
   就用这些

**Comment by Ewithome** [comment]
YYTextRubyAnnotation  没有用这啊

**Comment by ibireme** [comment]
你在你的项目里（包括用到的第三方库），全局搜索一下 `CTRubyAnnotationCreate` 这个方法，然后下断点看看是怎么被调用到的。

**Comment by ibireme** [comment]
还有，如果是崩溃的话，应该有崩溃日志，或者调试断点、函数调用栈之类的信息。
