### ISSUE TITLE
图片第一次没有展示，然后就一直不会展示，当切换界面后立马就展示图片

### ISSUE THREAD

**Issue by flytogcp** [ibireme/YYImage#8]

**Comment by ibireme** [comment]
不太懂，能给些更详细的描述或代码片段吗？

**Comment by flytogcp** [comment]
简单说就是，使用yy_setImageWithURL设置的图片，但是发现一直展示的默认图（这张图片之前确定下载过），等了很久还是没有展示图片，但是界面切换后（重新调用了yy_setImageWithURL），图片立马出来

**Comment by flytogcp** [comment]
![image](https://cloud.githubusercontent.com/assets/1559499/12029021/5f13309c-ae1c-11e5-92ea-af9f4da8dc06.png)
![image](https://cloud.githubusercontent.com/assets/1559499/12029047/e4345e72-ae1c-11e5-91db-1abbca830db3.png)
还会出现这种图片展示错乱和尺寸不对的问题！

**Comment by flytogcp** [comment]
提错地方了，我们用的是yywebimage

**Comment by flytogcp** [comment]
还有一个问题，typedef void (^YYWebImageCompletionBlock)(UIImage *image, NSURL *url, YYWebImageFromType from, YYWebImageStage stage, NSError *error);这个block里面返回的image，其实是yyimage，这个会导致+ (UIImage*)imageByApplyingBlurToImage:(UIImage*)inputImage withRadius:(CGFloat)blurRadius tintColor:(UIColor *)tintColor saturationDeltaFactor:(CGFloat)saturationDeltaFactor maskImage:(UIImage *)maskImage，这里处理后的模糊图片不正常，需要在block中转换为uiimage后才能展示正常

**Comment by ibireme** [comment]
首先请更新到最新版本的代码。

1. 图片不显示，这个问题描述太模糊不太好定位，这个可以在 completion block 里打印一下 image、from、stage、error 等参数看看。

2. 图片展示错乱这个，我觉得应该不是 YYWbImage 导致的，你可以检查下代码的调用顺序。图片下载后， YYWebImage 默认并不会调整图片尺寸，这个你应该检查下 UIImageView 的 contentMode 等属性配置。

3. YYImage 是 UIImage 的子类，理论上应该不会影响到后续处理。能说一下"不正常"是什么表现吗？

**Comment by flytogcp** [comment]
YYImage 是 UIImage 的子类，理论上应该不会影响到后续处理。能说一下"不正常"是什么表现吗？
就是Blur之后的效果是不一样的，差别很大

**Comment by flytogcp** [comment]
如果用sd_webImage就完全不存在上面提到的问题

**Comment by ibireme** [comment]
能问下你用的这几个库的版本号吗？

blur 那个方法，只会用到 CGImage 和 Scale 两个属性，这个 YYImage 和 UIImage 是一样的。我也测试了一下这个 blur 方法，表现也是一样的。

如果之前已经用了 SDWebImage 并且能满足需求，那就没必要换用这个库了嘛，毕竟接口和相关实现上有很多不一样的。
